version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      
  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "30000-30009:30000-30009" # passive FTP
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=user
      - FTP_USER_PASS=123
      - FTP_USER_HOME=/home/ftp
    volumes:
      - ./ftp-data:/home/ftp

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    ports:
      - "9999:9999"
    volumes:
      - .:/app
      - ./ftp-data:/usr/share/nginx/html:ro
    depends_on:
      - redis
      - mysql

volumes:
  mysql-data:
  redis-data:
  ftp-data: